class Base:
    __slots__: tuple[str, ...] = ...
    __hash_exclude__: tuple[str, ...] = ...
    __ignore_attr__: tuple[str, ...] = ...
    __ignore_copy__: tuple[Type, ...] = ...
    __ignore_kwarg__: tuple[str, ...] = ...
    __ignore_str__: tuple[Type, ...] = ...
    __repr_exclude__: tuple[str, ...] = ...
    __repr_newline__: bool = ...
    __repr_pproperty__: bool = ...
    def __getattribute__(self, name: str, default: Any = ...) -> Any: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def get(self, name: str, default: Union[Any, partial] = ...) -> Any: ...
    def _info(self,
             depth: Optional[int] = ...,
             ignore: bool = ...,
             key: Attr = ...) -> info: ...
    @property
    def info(self) -> info: ...
