class BaseMeta(type):
    infocls: InfoCls
    @overload
    def __new__(mcs, o: object) -> type: ...
    @overload
    def __new__(mcs, name: str, bases: tuple[type, ...], namespace: dict[str, Any]) -> type: ...
    def __class_getitem__(mcs, name: str) -> Union[Any, NotImplemented]: ...
