class InfoCls1(InfoClsBase):
    __slots__: tuple[str, ...] = ...
    def __new__(cls, data: Any)-> InfoCls: ...
    def data(self, key: Attr = ...) -> dict[str, Attribute]: ...
    def defaults(self, key: Attr = ...) -> dict[str, Any]: ...
    @singledispatchmethod
    def member(self, find: Attr = ...) -> dict[str, Attribute]: ...
    @member.register
    def member_es(self, find: Callable = ...) -> dict[str, Attribute]: ...
