class MetaType(Generic[_T]):
    _rv: list = ...
    infocls: Optional[InfoCls] = ...
    @property
    def rv(self) -> Any: ...
    @rv.setter
    def rv(self, value: Any) -> None: ...
    @rv.deleter
    def rv(self) -> None: ...
    __class_getitem__ = classmethod(GenericAlias)
    @classmethod
    def __subclasshook__(cls, C: Type) -> bool: ...
