
class slist(list, Seq[_SLT]):
    def __new__(cls, iterable: Iterable[_SLT] = ...) -> slist: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[_SLT] = ...) -> None: ...
    def __repr__(self) -> str: ...
