_STT = TypeVar('_STT')  # stuple
_STT_co = TypeVar('_STT_co', covariant=True)  # Any type covariant containers.

class stuple(tuple, MetaType, metaclass=Meta):
    __slots__: tuple[str, ...] = ...
    def __new__(cls, iterable: Iterable[_STT_co] = ...) -> stuple: ...
    def __repr__(self) -> str: ...
