class TestBase(Base):
    classvar: ClassVar[int] = ...
    initvar: InitVar[int] = ...
    __slots__: tuple[str, ...] = ...
    __hash_exclude__: tuple[str, ...] = ...
    __repr_exclude__: tuple[str, ...] = ...
    async def method_async(self) -> NoReturn: ...
    @classmethod
    def clsmethod(cls) -> NoReturn: ...
    @staticmethod
    def static() -> NoReturn: ...
    @pproperty
    def pprop(self) -> str: ...
    @pproperty
    async def pprop_async(self) -> str: ...
    @property
    def prop(self) -> Any: ...
    @prop.setter
    def prop(self, value: Any) -> None: ...
    @prop.deleter
    def prop(self) -> None: ...
