#!/usr/bin/env bash
export starting="${BASH_SOURCE[0]}"; debug.sh starting

unset PATH
PATH='/usr/bin:/usr/sbin:/bin:/sbin:.'

for dir in /Library/Developer/CommandLineTools/usr/bin \
            /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin \
            /usr/local/opt/ruby/bin \
            /Applications/PyCharm.app/Contents/MacOS \
            /usr/local/opt/python@3.8/bin; do
  ! test -d "${dir}" || PATH="${dir}:${PATH}"
done

if test -d "/home/linuxbrew/.linuxbrew/sbin"; then
  BREW_S="/home/linuxbrew/.linuxbrew/sbin"; PATH="${BREW_S}:${PATH}"
else
  BREW_S="/usr/local/sbin"
fi

if test -d "/home/linuxbrew/.linuxbrew/bin"; then
  BREW="/home/linuxbrew/.linuxbrew/bin"; PATH="${BREW}:${PATH}"
else
  BREW="/usr/local/bin"
fi

! test -n "${GOPATH}" || PATH="${GOPATH//://bin:}/bin:${PATH}"

for dir in "/usr/local/sbin" "/usr/local/bin" \
           "${PEN}/scripts" "${PEN}/bin" \
           "${USERHOME}/scripts" "${USERHOME}/bin" \
           "${ICLOUD}/bin" "${ICLOUD}/scripts" \
           "${MACDEV}/bin" "${MACDEV}/scripts"; do
  ! test -d "${dir}" || PATH="${dir}:${PATH}"
done

MANPATH="${BREW}/../share/man"
for dir in "${MACDEV}/man" "${ICLOUD}/man"; do
  ! test -d "${dir}" || MANPATH="${dir}:${MANPATH}"
done

INFOPATH="${BREW}/../share/info"
debug.sh PATH

if isuserdarwin.sh; then
  launchctl setenv PATH "${PATH}"
  sudo /bin/launchctl setenv PATH "${PATH}"
  sudo launchctl config system path "${PATH}" >/dev/null 2>&1
  sudo launchctl config user path "${PATH}" >/dev/null 2>&1
fi

debug.sh PATH INFOPATH MANPATH BREW
export PATH INFOPATH MANPATH BREW
unset starting dir
