#!/usr/bin/env bash
# shellcheck disable=SC1090
export starting="${BASH_SOURCE[0]}"; debug.sh starting

for source_name in bashrc-vars bashrc-dirs bashrc-aliases bashrc-functions bashrc-completions\
                   bashrc-iterm2 bashrc-misc; do
  source_path="$( command -v "${source_name}" )"; export source_path
  if test -f "${source_path}"; then
    debug.sh source_path
    source "${source_path}"
  else
    error.sh "${source_name}" "not found"; return 1
  fi
done

unset starting source_name source_path
