#!/usr/bin/env bash
# shellcheck disable=SC1090
export starting="${BASH_SOURCE[0]}"; debug.sh starting
DARWIN="$(uname -a | grep -i darwin 2>/dev/null)"; export DARWIN  ## First: home.sh uses it (USERHOME)
KALI="$(uname -a | grep -i kali 2>/dev/null)"; export KALI
DEBIAN="$(uname -a | grep -i debian 2>/dev/null)"; export DEBIAN
UBUNTU="$(uname -a | grep -i ubuntu 2>/dev/null)"; export UBUNTU

export KALI_IP="35.153.66.76"
export HP_IP="192.168.1.10"

export USERNAME="jose"
USERHOME="$( home.sh "${USERNAME}" )"; export USERHOME
export PASSWD_PATH="${USERHOME}/.passwd"
export BASHRC_FILE="bashrc"
export PROJECT_BASHRC="${USERHOME}/bashrc"
export GITHUB_USERNAME="j5pu"
export GITHUB_EMAIL="${GITHUB_USERNAME}@github.com"
export GITHUB_URL="https://github.com/${GITHUB_USERNAME}"
export GITHUB_ORGANIZATION="lumenbiomics"
export GITHUB_ORGANIZATION_ID="org-4379404"
export GITHUB_ORGANIZATION_CLONE_PREFIX_HTTP="https://github.com/${GITHUB_ORGANIZATION}"
export GITHUB_ORGANIZATION_ID_CLONE_PREFIX_SSH="${GITHUB_ORGANIZATION_ID}@github.com:"
export GITHUB_ORGANIZATION_CLONE_PREFIX_SSH="${GITHUB_ORGANIZATION_ID_CLONE_PREFIX_SSH}${GITHUB_ORGANIZATION}"
export GITHUB_SECRETS_PATH="${USERHOME}/.ssh"
export GIT_CONFIG="${GITHUB_SECRETS_PATH}/gitconfig"
export GIT_STORE="${GITHUB_SECRETS_PATH}/credentials"
export ATHENS_GONOSUM_PATTERNS="github.com/${GITHUB_ORGANIZATION}/*"
export GONOSUMDB="github.com/${GITHUB_ORGANIZATION}/*,github.com/secret/*"
export NFERX_GITHUB_USERNAME="jose-nferx"
export SECRETS_REPO="secrets"
export SECRETS_PATH="${GITHUB_SECRETS_PATH}/secrets"
export PEN_BASENAME="pen"
export ICLOUD_BASENAME="iCloud"
export MACDEV_BASENAME="macdev"
export ICLOUD="${USERHOME}/${ICLOUD_BASENAME}"
export GOHOME="${USERHOME}/.go"

PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
INFOPATH="${BREW}/../share/info"
MANPATH="${BREW}/../share/man"
if test -n "${DARWIN}"; then
  MACDEV="$( defaults read "${USERHOME}/Library/Preferences/com.google.GoogleDrive.plist" NSNavLastRootDirectory | sed "s|~|${USERHOME}|" )"; export MACDEV
  export FILES="${MACDEV}/files"
  export REQUESTS_CA_BUNDLE="${FILES}/ssl/ca-bundle.crt"
  export DEFAULT_CA_BUNDLE_PATH="${REQUESTS_CA_BUNDLE}"
  export SSL_CERT_FILE="${REQUESTS_CA_BUNDLE}"
  PEN="${USERHOME}/${PEN_BASENAME}"
  BREW="/usr/local/bin"
  BREW_S="/usr/local/sbin"
  PATH="${PEN}:${PEN}/bin:${PEN}/scripts:${MACDEV}/scripts:${MACDEV}/bin:${ICLOUD}/bin:${USERHOME}/bin:/Applications/PyCharm.app/Contents/MacOS:/usr/local/opt/ruby/bin:/usr/local/opt/python@3.8/bin:/Library/Developer/CommandLineTools/usr/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:${PATH}"
  MANPATH="${MACDEV}/man:${ICLOUD}/man:${MANPATH}"
elif test -n "${KALI}"; then
  export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
  PEN="/${PEN_BASENAME}"
  BREW="/home/linuxbrew/.linuxbrew/bin"
  BREW_S="/home/linuxbrew/.linuxbrew/sbin"
  PATH="${PEN}:${PEN}/bin:${PEN}/scripts:${BREW}:${BREW_S}:${PATH}"
fi
MANPATH="${MACDEV}/man:${ICLOUD}/man:${BREW}/../share/man"
export PATH PEN BREW INFOPATH MANPATH

! test -e "${PASSWD_PATH}" || source "${PASSWD_PATH}"
echo "${PASSWORD}" | sudo -S true > /dev/null 2>&1
! test -e "${SECRETS_PATH}" || source "${SECRETS_PATH}"

if isuserdarwin.sh; then
  launchctl setenv PATH "${PATH}"
  sudo launchctl setenv PATH "${PATH}"
  sudo launchctl config system path "${PATH}" >/dev/null 2>&1
  sudo launchctl config user path "${PATH}" >/dev/null 2>&1
fi

for var in USERNAME USERHOME PASSWD_PATH BASHRC_FILE PROJECT_BASHRC GITHUB_USERNAME NFERX_GITHUB_USERNAME \
           SECRETS_REPO GITHUB_SECRETS_PATH SECRETS_PATH PASSWORD INTERNET GITHUB_PRIVATE_URL \
           GITHUB_SECRETS_URL NFERX_GITHUB_PASSWORD; do
  debug.sh "${var}"
done

unset starting var
