#!/usr/bin/env bash
# shellcheck disable=SC1090
# shellcheck disable=SC2155
export DOCKER_HOST=ssh://kali.com
export PASSWD_PATH="${USERHOME}/.passwd"
export GITHUB_DOMAIN="github.com"
export GITHUB_EMAIL="${GITHUB_USER}@${GITHUB_DOMAIN}"
export GITHUB_URL="https://${GITHUB_DOMAIN}/${GITHUB_USER}"
export GITHUB_SECRETS_PATH="${USERHOME}/.ssh"
export GIT_STORE="${GITHUB_SECRETS_PATH}/gitcredentials"
# shellcheck disable=SC2153
export ATHENS_GONOSUM_PATTERNS="${GITHUB_DOMAIN}/${GITHUB_ORG}/*"
export SECRETS_REPO="secrets"
export SECRETS_PATH="${GITHUB_SECRETS_PATH}/secrets"
export ICLOUD="${USERHOME}/${ICLOUD_BASENAME}"
export GIT_COMMAND="git"
export GIT_PREFIX="${GIT_COMMAND}@${GITHUB_DOMAIN}.com:"
export INTERNET_HASH="$(! command -v openssl >/dev/null 2>&1 || openssl passwd -1 -salt xyz "${INTERNET}")"
export PS1_SSH_THE_SAME="yes"
export SETENV="no"
export SHELLCHECK_OPTS="--shell=bash"
export SSH_ARGS='-o ControlMaster=auto -o CheckHostIP=no -o BatchMode=yes -o ControlPersist=20m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
export BASH_RC_PROJECT="${USERHOME}/${BASH_RC_NAME}"
export VISUAL="/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"
export REPOS="${MACDEV}/repos"
export MSF_DATABASE_CONFIG="${USERHOME}/msf4/db"
