#!/usr/bin/env bash
# shellcheck disable=SC2155
export starting="${BASH_SOURCE[0]}"; debug.sh starting
[[ ! "${TIMES-}" ]] || start="$( date +%s )"

export ANSIBLE="${USERHOME}/ansible"
export BAPY="${USERHOME}/bapy"
export CLONES="${USERHOME}/clones"
export EXAMPLES="${USERHOME}/examples"
export LIBRARY="${USERHOME}/Library"
export LOG="${USERHOME}/log"
export MNOPI="${USERHOME}/mnopi"
export PEN="${USERHOME}/pen"
export SCRATCHES="${USERHOME}/${SCRATCHES_NAME}"
export SERVERS="${USERHOME}/servers"
export BASH_RC_PROJECT="${USERHOME}/${BASH_RC_NAME}"

export VISUAL="/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron"

export CACHES="${LIBRARY}/Caches"
export MOBILE="${LIBRARY}/Mobile Documents"
export PREFS="${LIBRARY}/Preferences"
export SAVED="${LIBRARY}/Saved Application State"
export SUPPORT="${LIBRARY}/Application Support"

export KEYNOTE="${MOBILE}/com~apple~Keynote/Documents"
export NUMBERS="${MOBILE}/com~apple~Numbers/Documents"
export PAGES="${MOBILE}/com~apple~Pages/Documents"

export JETBRAINS="${SUPPORT}/${JETBRAINS_NAME}"
export PYCHARM="${JETBRAINS}/${PYCHARM_NAME}${PYCHARM_VERSION}"
export PYCHARM_OPTIONS="${PYCHARM}/options"
export PYCHARM_SCRATCHES="${PYCHARM}/${SCRATCHES_NAME}"
export PYCHARM_PLUGINS="${PYCHARM}/plugins"

export VARLOG_BASENAME="${USERNAME}"
export VARLOG="/var/log/${USERNAME}"
sudo mkdir -p "${VARLOG}" >/dev/null 2>&1
sudo chown -R "${USERNAME}":"$( id -g "${USERNAME}" )" "${VARLOG}" >/dev/null 2>&1
sudo /bin/chmod -R g+s "${VARLOG}"

export APPLICATIONS="${MACDEV}/applications"
export PACKAGES="${MACDEV}/packages"
export REPOS="${MACDEV}/repos"
export SCRIPTS="${MACDEV}/scripts"

export MSF_DATABASE_CONFIG="${USERHOME}/msf4/db"

export BREWFILE="${PACKAGES}/Brewfile"
export GEMFILE="${PACKAGES}/Gemfile"
export NPMFILE="${PACKAGES}/npmfile"
export OPAMFILE="${PACKAGES}/Opamfile"
export USERFILE="${PACKAGES}/Userfile"
export REQUIREMENTS="${PACKAGES}/requirements.txt"

export USB="/Volumes/USB-2TB"
export TIME="${USB}/Backups.backupdb/$( hostname )"
export DATA="$( [[ "$(uname -s)" == "Darwin" ]] && diskutil info disk1s1 | grep "Volume Name" | awk '{$1=$2=""; print $0}' | sed 's/^ *//g' || echo )"
export LATEST="${TIME}/Latest/${DATA}"

export SYNTHETIC="${USERHOME}/Desktop ${USERHOME}/Documents ${USERHOME}/Downloads ${MACDEV} ${ICLOUD} ${PEN}"
export DOCK="${USERHOME} ${ALL} ${USERHOME}/Desktop ${USERHOME}/Documents ${ICLOUD} ${LIBRARY} ${PEN} ${DRIVE} ${USERHOME}/Downloads"
[[ ! "${TIMES-}" ]] || { end="$( date +%s )"; export runtime=$((end-start)); times.sh starting runtime; }
unset start end runtime

unset starting
