#!/usr/bin/env bash
# shellcheck disable=SC1090
# shellcheck disable=SC2155
export starting="${BASH_SOURCE[0]}"; debug.sh starting

DARWIN="$(uname -a | grep -i darwin 2>/dev/null)"; export DARWIN  ## First: home.sh uses it (USERHOME)
KALI="$(uname -a | grep -i kali 2>/dev/null)"; export KALI
DEBIAN="$(uname -a | grep -i debian 2>/dev/null)"; export DEBIAN
UBUNTU="$(uname -a | grep -i ubuntu 2>/dev/null)"; export UBUNTU

export USERNAME="jose"
USERHOME="$( home.sh "${USERNAME}" )"; export USERHOME
export PASSWD_PATH="${USERHOME}/.passwd"
export GITHUB_USERNAME="j5pu"
export GITHUB_DOMAIN="github.com"
export GITHUB_EMAIL="${GITHUB_USERNAME}@${GITHUB_DOMAIN}"
export GITHUB_URL="https://${GITHUB_DOMAIN}/${GITHUB_USERNAME}"
export GITHUB_SECRETS_PATH="${USERHOME}/.ssh"
export GIT_STORE="${GITHUB_SECRETS_PATH}/gitcredentials"
export ATHENS_GONOSUM_PATTERNS="${GITHUB_DOMAIN}/${GITHUB_ORGANIZATION}/*"
export SECRETS_REPO="secrets"
export SECRETS_PATH="${GITHUB_SECRETS_PATH}/secrets"
export ICLOUD_BASENAME="iCloud"
export MACDEV_BASENAME="macdev"
if test -n "${DARWIN}"; then
#  DRIVE="$( defaults read "${USERHOME}/Library/Preferences/com.google.GoogleDrive.plist" NSNavLastRootDirectory \
#             | sed "s|~|${USERHOME}|" )"
  MACDEV="${HOME}/${MACDEV_BASENAME}"; export MACDEV
  REALNAME="$( dscl . -read /Users/"${USERNAME}" RealName RealName | sed -n 's/^ //g;2p' )"
  export PYCHARM_NAME='PyCharm'
  _v="$( defaults read /Applications/${PYCHARM_NAME}.app/Contents/Info.plist CFBundleShortVersionString )"
  export PYCHARM_VERSION="${_v%.*}"
  unset _v
else
  REALNAME="$( id -nu )"

fi
export REALNAME
export ICLOUD="${USERHOME}/${ICLOUD_BASENAME}"
export GOHOME="${USERHOME}/.go"
export GOPATH="${GOHOME}/bin"
export AMARILLO="\[\033[1;33m\]"

export ANSIBLE_SUDO_PASSWORD="${INTERNET}"

export AZUL="\[\033[1;34m\]"
export AZULCLARO="\[\033[1;36m\]"

export CLICOLOR=1
export CLT="/Library/Developer/CommandLineTools"

export DEFAULT_KALI_USER='kali'

export DOCKER_HOST=ssh://kali.com

export EDITOR=vi

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

export GIT_COMMAND="git"
export GIT_PREFIX="${GIT_COMMAND}@${GITHUB_DOMAIN}.com:"
export GITHUB_DESKTOP_PROCESS="GitHub Desktop"
export GITHUB_DESKTOP="/Applications/${GITHUB_DESKTOP_PROCESS}.app"

export GO111MODULE=on

export GREP_COLORS='ms=01;31:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'
export HISTSIZE=999999
export HISTFILESIZE=999999

export ICLOUD_NICK="i"

export INTERNET_HASH="$(! command -v openssl >/dev/null 2>&1 || openssl passwd -1 -salt xyz "${INTERNET}")"

export INVERSO="\[\033[00m\]"

export JETBRAINS_NAME='JetBrains'

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LIBRARY_NICK="l"

export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

export MACDEV_NICK="m"

export MACKUP_ENGINE="file_system" # dropbox, google_drive, icloud and file_system

export MACROOT="/System/Volumes/Data"
export MORADO="\[\033[1;35m\]"

export PACKAGES_BASENAME="packages"

export PEN_NICK="p"

export PROMPT_COMMAND='history -a;history -r'

export PS1_SSH_THE_SAME="yes"
export PS4="$(tty -s && tput setaf 5)+\$(echo \${BASH_SOURCE[0]}:\${LINENO}) $(tty -s && tput setaf 3)\$(echo \${LINENO} | sed 's/\$/@/g')\$(echo \${BASH_LINENO[*]} | awk '{\$NF=\"\"; print \$0}' | sed 's/ \$//g'| sed 's/ /@/g')$(tty -s && tput sgr0):$(tty -s && tput setaf 5)\$(echo \${FUNCNAME[*]} | sed 's/ /\//g')$(tty -s && tput sgr0)$ "

export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export PYTHONASYNCIODEBUG=0
export PYTHONNOUSERSITE=0

export ROJO="\[\033[1;31m\]"

export SCRATCHES_NAME='scratches'
export SCRIPTS_BASENAME="scripts"
export SCHEME="https"

export SETENV="no"
export SHELLCHECK_OPTS='--shell=bash'
export SSH_ARGS='-o ControlMaster=auto -o CheckHostIP=no -o BatchMode=yes -o ControlPersist=20m -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
export TERM="xterm-256color"
export TERM_PROGRAM='iTerm.app'
export VERDE="\[\033[1;32m\]"
export VISUAL=vi

unset starting
