#!/usr/bin/env bash
export starting="${BASH_SOURCE[0]}"; debug.sh starting
[[ ! "${TIMES-}" ]] || start="$( date +%s )"

if test -n "${DARWIN}"; then
  export FILES="${MACDEV}/files"
  export REQUESTS_CA_BUNDLE="${FILES}/ssl/ca-bundle.crt"
  export DEFAULT_CA_BUNDLE_PATH="${REQUESTS_CA_BUNDLE}"
  export SSL_CERT_FILE="${REQUESTS_CA_BUNDLE}"
elif test -n "${KALI}"; then
  export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
fi
[[ ! "${TIMES-}" ]] || { end="$( date +%s )"; export runtime=$((end-start)); times.sh starting runtime; }
unset start end runtime

unset starting
